#!/bin/bash
# A script to automate the process of provisioning servers

if [ !$PROVISIONUPDATED ]; then # If provision script hasn't already been updated
	echo "Checking if provision script is up to date."
	cd ~/Scripts/
	git pull
	export PROVISIONUPDATED=True # Set enviromental variable, so we don't have to do this again
	exec ~/Scripts/sudo-only/provision-server # Restart provision script
fi

read -p "Enter Hostname: " hostname
hostnamectl hostname "$hostname"
echo "hostname updated"
read -p "Enter Tailscale Auth Key: \n(Found in Tailscale admin console -> Add device -> Linux Server - > Generate Install Script -> --auth-key=[copy this part])" tsAuthKey
tailscale up --auth-key="$tsAuthKey"
echo "Server added to tailnet"
echo "Updating DNF Packages"
dnf update
echo "Deleting Symlink to this script"
rm /root/provision-server
echo "All done, Rebooting in 10 seconds!"
sleep 10
reboot
