#!/bin/bash
# A little update script - Ellie Schaefer - 4/30/2024

server=false

while getopts ":s" option; do
	case $option in
		s) server=true ;;
		\?) echo "Invalid option: -$OPTARG"; usage; exit 1;;
	esac
done

echo "Updating DNF Packages"
sudo dnf update
if [ $? -ne 0 ]
then
	echo "DNF update failed, stopping now." >&2
	exit 1
fi

if not "$server"
then
	echo "Updating FlatPak Packages"
	flatpak update -y	# Assume yes
	if [ $? -ne 0 ]
	then
		echo "Flatpak update failed, stopping now." >&2
		exit 1
	fi
fi

echo "Updating Dotfiles..."
cd ~/Dotfiles
git pull
if [ $? -ne 0 ]
then
	echo "Dotfile update failed, stopping now." >&2
	exit 1
fi

echo "Updating Scripts..."
cd ~/Scripts
git pull
if [ $? -ne 0 ]
then
	echo "Scripts update failed, stopping now." >&2
	exit 1
fi

echo "all done!"
exit 0
